NHSDigital/gp-registrations-management-information-api

proxies/live/apiproxy/targets/gprmi-target.xml
* :sparkles:  Configure target endpoint to point to dev API
=> PRMT-2396 [HZ/SP/JG] Update target endpoint to point to dev API gateway URL

proxies/live/apiproxy/targets/gprmi-target.xml
* :sparkles:  Configure target endpoint to point to dev API
=> PRMT-2396 [HZ/AB] Update target endpoint URL to use HTTPS

azure/azure-release-pipeline.yml
=> PRMT-2425 [SP/JN/AB] Add int environment on azure-release-pipeline

azure/azure-release-pipeline.yml, manifest_template.yml
=> Prmt-2425 config for prod

azure/azure-release-pipeline.yml, proxies/live/apiproxy/targets/gprmi-target.xml
=> PRMT-2425 [SP/AB] Add target url based on environment

specification/gp-registrations-management-information.yaml
=> PRMT-2445 [AB/DS] Add version to the path

specification/gp-registrations-management-information.yaml
=> PRMT-2444 [AB] Update the description of the API spec

specification/gp-registrations-management-information.yaml
=> PRMT-2444 [AB] Update the description to add more sections about our API

specification/gp-registrations-management-information.yaml
=> PRMT-2444 [AB] Update overview description to expand on types of events

specification/gp-registrations-management-information.yaml
=> PRMT-2444 [JN/AB] Update overview description to add more events

specification/gp-registrations-management-information.yaml
=> PRMT-2509 [IG] Add GPConnect information to the general overview

specification/gp-registrations-management-information.yaml
=> PRMT-2509 [IG] Remove linting problems

specification/components/responses/BadRequest.yaml, specification/components/responses/InternalServerError.yaml, specification/components/responses/OK.yaml
=> PRMT-2509 [IG] Add more info into the response examples

specification/gp-registrations-management-information.yaml
=> Prmt 2510d

specification/gp-registrations-management-information.yaml
=> Prmt 2510e

specification/gp-registrations-management-information.yaml
=> Prmt 2510f

specification/gp-registrations-management-information.yaml
=> Prmt 2510g

specification/gp-registrations-management-information.yaml
=> Prmt 2510h

specification/gp-registrations-management-information.yaml
=> PRMT-2510 [IG] Make the fields for the initial registration required

specification/components/schemas/StatusDetails.yaml, specification/gp-registrations-management-information.yaml
=> Prmt 2510j

specification/gp-registrations-management-information.yaml
=> PRMT-2510 [IG] Add mailto tag to onboarding email

azure/azure-pr-pipeline.yml, specification/gp-registrations-management-information.yaml
=> Prmt 2623b

manifest_template.yml, proxies/live/apiproxy/policies/SpikeArrest.xml
=> PRMT-2548 increase rate limit 10000

azure/azure-pr-pipeline.yml, azure/azure-release-pipeline.yml, proxies/live/apiproxy/policies/FlowCallout.GetEnvironmentKeyValueMapData.xml, proxies/live/apiproxy/policies/ServiceCallout.CallHealthcheckEndpoint.xml, proxies/live/apiproxy/proxies/default.xml
=> PRMT-2755 [JN] Point HealthCheckEndpoint to the MI API

specification/components/schemas/DocumentMigration.yaml, specification/gp-registrations-management-information.yaml
Change documentMigration.status to documentMigration.successful as a boolean instead of Enum
=> PRMT-2767 [JN] Add schema for documentMigration

specification/components/responses/InternalServerError.yaml, specification/components/schemas/DocumentMigration.yaml, specification/gp-registrations-management-information.yaml
=> PRMT-2283 [JN] Update to latest spec (should be final)

specification/gp-registrations-management-information.yaml
=> PRMT-2923 [JN] Update status and service level content

.github/workflows/continuous-integration.yml, .github/workflows/pr-lint.yaml, manifest_template.yml
part of the process of moving identify provider from nhs-id to nhs-cis2
=> added cis2 scope to manifest

specification/gp-registrations-management-information.yaml
Update the default URL used to accss the Path to Live Integration environment so the Try it now link in the documentation will work.
=> PRMT-3036 [JN/JP] Updated server url for api-catalogue

specification/gp-registrations-management-information.yaml
Refinement of API documentation to correct the api url to be a pural.
=> PRMT-3036 [JN/JP] Update paths to correctly reflect api (gp-registrations-mi/)

specification/gp-registrations-management-information.yaml
=> PRMT-3086 [JN/JP] Fix typo in Compatibility

.github/workflows/continuous-integration.yml, azure/templates/run-smoke-tests.yml, azure/templates/setup-proxygen-cli.yml, poetry.lock, pyproject.toml, scripts/calculate_version.py
=> APM-3594 Restore version tag script

specification/gp-registrations-management-information.yaml
Update broken link to gp2gp v2.2 spec
=> Update gp2gp spec link

azure/templates/setup-proxygen-cli.yml
=> reading and supplying KID to proxygen creds

azure/templates/setup-proxygen-cli.yml
=> Apm 000 fix gpregmi proxygen creds

.github/workflows/continuous-integration.yml, azure/azure-build-pipeline.yml, azure/azure-pr-pipeline.yml, azure/templates/run-smoke-tests.yml, azure/templates/setup-proxygen-cli.yml, poetry.lock, pyproject.toml
Requires bump of python version to 3.9
Also include poetry.lock as is best practice
=> Update proxygen-cli to latest

README.md, azure/templates/deploy-env-proxy.yml, specification/gp-registrations-management-information.yaml
=> dummy change

specification/gp-registrations-management-information.yaml
Added link to error codes that are defined on the Gp2GP specification
=> Update Errors section of spec to include link to error codes

specification/components/schemas/Error.yaml
Update errorCode description to state that it should only contain letters, numbers and underscores and also only be 50 characters in length.
=> Update errorCode description

specification/components/schemas/Placeholder.yaml
Fix link for GP2GP Handling missing attachments pdf document
=> Update link to handling missing attachments pdf

azure/templates/setup-proxygen-cli.yml, specification/components/schemas/Placeholder.yaml
First fix proxygen deployment issues
=> APM-5087 Fixing deployment pipeline issues
